// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// Source: google/protobuf/wrappers.proto
/* eslint-disable */

import type { ByteSource, PartialDeep } from "protoscript";
import * as protoscript from "protoscript";

//========================================//
//                 Types                  //
//========================================//

/**
 * Wrapper message for `double`.
 *
 * The JSON representation for `DoubleValue` is JSON number.
 */
export interface DoubleValue {
  /**
   * The double value.
   */
  value: number;
}

/**
 * Wrapper message for `float`.
 *
 * The JSON representation for `FloatValue` is JSON number.
 */
export interface FloatValue {
  /**
   * The float value.
   */
  value: number;
}

/**
 * Wrapper message for `int64`.
 *
 * The JSON representation for `Int64Value` is JSON string.
 */
export interface Int64Value {
  /**
   * The int64 value.
   */
  value: bigint;
}

/**
 * Wrapper message for `uint64`.
 *
 * The JSON representation for `UInt64Value` is JSON string.
 */
export interface UInt64Value {
  /**
   * The uint64 value.
   */
  value: bigint;
}

/**
 * Wrapper message for `int32`.
 *
 * The JSON representation for `Int32Value` is JSON number.
 */
export interface Int32Value {
  /**
   * The int32 value.
   */
  value: number;
}

/**
 * Wrapper message for `uint32`.
 *
 * The JSON representation for `UInt32Value` is JSON number.
 */
export interface UInt32Value {
  /**
   * The uint32 value.
   */
  value: number;
}

/**
 * Wrapper message for `bool`.
 *
 * The JSON representation for `BoolValue` is JSON `true` and `false`.
 */
export interface BoolValue {
  /**
   * The bool value.
   */
  value: boolean;
}

/**
 * Wrapper message for `string`.
 *
 * The JSON representation for `StringValue` is JSON string.
 */
export interface StringValue {
  /**
   * The string value.
   */
  value: string;
}

/**
 * Wrapper message for `bytes`.
 *
 * The JSON representation for `BytesValue` is JSON string.
 */
export interface BytesValue {
  /**
   * The bytes value.
   */
  value: Uint8Array;
}

//========================================//
//        Protobuf Encode / Decode        //
//========================================//

export const DoubleValue = {
  /**
   * Serializes DoubleValue to protobuf.
   */
  encode: function (msg: PartialDeep<DoubleValue>): Uint8Array {
    return DoubleValue._writeMessage(
      msg,
      new protoscript.BinaryWriter(),
    ).getResultBuffer();
  },

  /**
   * Deserializes DoubleValue from protobuf.
   */
  decode: function (bytes: ByteSource): DoubleValue {
    return DoubleValue._readMessage(
      DoubleValue.initialize(),
      new protoscript.BinaryReader(bytes),
    );
  },

  /**
   * Initializes DoubleValue with all fields set to their default value.
   */
  initialize: function (msg?: Partial<DoubleValue>): DoubleValue {
    return {
      value: 0,
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<DoubleValue>,
    writer: protoscript.BinaryWriter,
  ): protoscript.BinaryWriter {
    if (msg.value) {
      writer.writeDouble(1, msg.value);
    }
    return writer;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: DoubleValue,
    reader: protoscript.BinaryReader,
  ): DoubleValue {
    while (reader.nextField()) {
      const field = reader.getFieldNumber();
      switch (field) {
        case 1: {
          msg.value = reader.readDouble();
          break;
        }
        default: {
          reader.skipField();
          break;
        }
      }
    }
    return msg;
  },
};

export const FloatValue = {
  /**
   * Serializes FloatValue to protobuf.
   */
  encode: function (msg: PartialDeep<FloatValue>): Uint8Array {
    return FloatValue._writeMessage(
      msg,
      new protoscript.BinaryWriter(),
    ).getResultBuffer();
  },

  /**
   * Deserializes FloatValue from protobuf.
   */
  decode: function (bytes: ByteSource): FloatValue {
    return FloatValue._readMessage(
      FloatValue.initialize(),
      new protoscript.BinaryReader(bytes),
    );
  },

  /**
   * Initializes FloatValue with all fields set to their default value.
   */
  initialize: function (msg?: Partial<FloatValue>): FloatValue {
    return {
      value: 0,
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<FloatValue>,
    writer: protoscript.BinaryWriter,
  ): protoscript.BinaryWriter {
    if (msg.value) {
      writer.writeFloat(1, msg.value);
    }
    return writer;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: FloatValue,
    reader: protoscript.BinaryReader,
  ): FloatValue {
    while (reader.nextField()) {
      const field = reader.getFieldNumber();
      switch (field) {
        case 1: {
          msg.value = reader.readFloat();
          break;
        }
        default: {
          reader.skipField();
          break;
        }
      }
    }
    return msg;
  },
};

export const Int64Value = {
  /**
   * Serializes Int64Value to protobuf.
   */
  encode: function (msg: PartialDeep<Int64Value>): Uint8Array {
    return Int64Value._writeMessage(
      msg,
      new protoscript.BinaryWriter(),
    ).getResultBuffer();
  },

  /**
   * Deserializes Int64Value from protobuf.
   */
  decode: function (bytes: ByteSource): Int64Value {
    return Int64Value._readMessage(
      Int64Value.initialize(),
      new protoscript.BinaryReader(bytes),
    );
  },

  /**
   * Initializes Int64Value with all fields set to their default value.
   */
  initialize: function (msg?: Partial<Int64Value>): Int64Value {
    return {
      value: 0n,
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<Int64Value>,
    writer: protoscript.BinaryWriter,
  ): protoscript.BinaryWriter {
    if (msg.value) {
      writer.writeInt64String(1, msg.value.toString() as any);
    }
    return writer;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: Int64Value,
    reader: protoscript.BinaryReader,
  ): Int64Value {
    while (reader.nextField()) {
      const field = reader.getFieldNumber();
      switch (field) {
        case 1: {
          msg.value = BigInt(reader.readInt64String());
          break;
        }
        default: {
          reader.skipField();
          break;
        }
      }
    }
    return msg;
  },
};

export const UInt64Value = {
  /**
   * Serializes UInt64Value to protobuf.
   */
  encode: function (msg: PartialDeep<UInt64Value>): Uint8Array {
    return UInt64Value._writeMessage(
      msg,
      new protoscript.BinaryWriter(),
    ).getResultBuffer();
  },

  /**
   * Deserializes UInt64Value from protobuf.
   */
  decode: function (bytes: ByteSource): UInt64Value {
    return UInt64Value._readMessage(
      UInt64Value.initialize(),
      new protoscript.BinaryReader(bytes),
    );
  },

  /**
   * Initializes UInt64Value with all fields set to their default value.
   */
  initialize: function (msg?: Partial<UInt64Value>): UInt64Value {
    return {
      value: 0n,
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<UInt64Value>,
    writer: protoscript.BinaryWriter,
  ): protoscript.BinaryWriter {
    if (msg.value) {
      writer.writeUint64String(1, msg.value.toString() as any);
    }
    return writer;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: UInt64Value,
    reader: protoscript.BinaryReader,
  ): UInt64Value {
    while (reader.nextField()) {
      const field = reader.getFieldNumber();
      switch (field) {
        case 1: {
          msg.value = BigInt(reader.readUint64String());
          break;
        }
        default: {
          reader.skipField();
          break;
        }
      }
    }
    return msg;
  },
};

export const Int32Value = {
  /**
   * Serializes Int32Value to protobuf.
   */
  encode: function (msg: PartialDeep<Int32Value>): Uint8Array {
    return Int32Value._writeMessage(
      msg,
      new protoscript.BinaryWriter(),
    ).getResultBuffer();
  },

  /**
   * Deserializes Int32Value from protobuf.
   */
  decode: function (bytes: ByteSource): Int32Value {
    return Int32Value._readMessage(
      Int32Value.initialize(),
      new protoscript.BinaryReader(bytes),
    );
  },

  /**
   * Initializes Int32Value with all fields set to their default value.
   */
  initialize: function (msg?: Partial<Int32Value>): Int32Value {
    return {
      value: 0,
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<Int32Value>,
    writer: protoscript.BinaryWriter,
  ): protoscript.BinaryWriter {
    if (msg.value) {
      writer.writeInt32(1, msg.value);
    }
    return writer;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: Int32Value,
    reader: protoscript.BinaryReader,
  ): Int32Value {
    while (reader.nextField()) {
      const field = reader.getFieldNumber();
      switch (field) {
        case 1: {
          msg.value = reader.readInt32();
          break;
        }
        default: {
          reader.skipField();
          break;
        }
      }
    }
    return msg;
  },
};

export const UInt32Value = {
  /**
   * Serializes UInt32Value to protobuf.
   */
  encode: function (msg: PartialDeep<UInt32Value>): Uint8Array {
    return UInt32Value._writeMessage(
      msg,
      new protoscript.BinaryWriter(),
    ).getResultBuffer();
  },

  /**
   * Deserializes UInt32Value from protobuf.
   */
  decode: function (bytes: ByteSource): UInt32Value {
    return UInt32Value._readMessage(
      UInt32Value.initialize(),
      new protoscript.BinaryReader(bytes),
    );
  },

  /**
   * Initializes UInt32Value with all fields set to their default value.
   */
  initialize: function (msg?: Partial<UInt32Value>): UInt32Value {
    return {
      value: 0,
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<UInt32Value>,
    writer: protoscript.BinaryWriter,
  ): protoscript.BinaryWriter {
    if (msg.value) {
      writer.writeUint32(1, msg.value);
    }
    return writer;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: UInt32Value,
    reader: protoscript.BinaryReader,
  ): UInt32Value {
    while (reader.nextField()) {
      const field = reader.getFieldNumber();
      switch (field) {
        case 1: {
          msg.value = reader.readUint32();
          break;
        }
        default: {
          reader.skipField();
          break;
        }
      }
    }
    return msg;
  },
};

export const BoolValue = {
  /**
   * Serializes BoolValue to protobuf.
   */
  encode: function (msg: PartialDeep<BoolValue>): Uint8Array {
    return BoolValue._writeMessage(
      msg,
      new protoscript.BinaryWriter(),
    ).getResultBuffer();
  },

  /**
   * Deserializes BoolValue from protobuf.
   */
  decode: function (bytes: ByteSource): BoolValue {
    return BoolValue._readMessage(
      BoolValue.initialize(),
      new protoscript.BinaryReader(bytes),
    );
  },

  /**
   * Initializes BoolValue with all fields set to their default value.
   */
  initialize: function (msg?: Partial<BoolValue>): BoolValue {
    return {
      value: false,
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<BoolValue>,
    writer: protoscript.BinaryWriter,
  ): protoscript.BinaryWriter {
    if (msg.value) {
      writer.writeBool(1, msg.value);
    }
    return writer;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: BoolValue,
    reader: protoscript.BinaryReader,
  ): BoolValue {
    while (reader.nextField()) {
      const field = reader.getFieldNumber();
      switch (field) {
        case 1: {
          msg.value = reader.readBool();
          break;
        }
        default: {
          reader.skipField();
          break;
        }
      }
    }
    return msg;
  },
};

export const StringValue = {
  /**
   * Serializes StringValue to protobuf.
   */
  encode: function (msg: PartialDeep<StringValue>): Uint8Array {
    return StringValue._writeMessage(
      msg,
      new protoscript.BinaryWriter(),
    ).getResultBuffer();
  },

  /**
   * Deserializes StringValue from protobuf.
   */
  decode: function (bytes: ByteSource): StringValue {
    return StringValue._readMessage(
      StringValue.initialize(),
      new protoscript.BinaryReader(bytes),
    );
  },

  /**
   * Initializes StringValue with all fields set to their default value.
   */
  initialize: function (msg?: Partial<StringValue>): StringValue {
    return {
      value: "",
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<StringValue>,
    writer: protoscript.BinaryWriter,
  ): protoscript.BinaryWriter {
    if (msg.value) {
      writer.writeString(1, msg.value);
    }
    return writer;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: StringValue,
    reader: protoscript.BinaryReader,
  ): StringValue {
    while (reader.nextField()) {
      const field = reader.getFieldNumber();
      switch (field) {
        case 1: {
          msg.value = reader.readString();
          break;
        }
        default: {
          reader.skipField();
          break;
        }
      }
    }
    return msg;
  },
};

export const BytesValue = {
  /**
   * Serializes BytesValue to protobuf.
   */
  encode: function (msg: PartialDeep<BytesValue>): Uint8Array {
    return BytesValue._writeMessage(
      msg,
      new protoscript.BinaryWriter(),
    ).getResultBuffer();
  },

  /**
   * Deserializes BytesValue from protobuf.
   */
  decode: function (bytes: ByteSource): BytesValue {
    return BytesValue._readMessage(
      BytesValue.initialize(),
      new protoscript.BinaryReader(bytes),
    );
  },

  /**
   * Initializes BytesValue with all fields set to their default value.
   */
  initialize: function (msg?: Partial<BytesValue>): BytesValue {
    return {
      value: new Uint8Array(),
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<BytesValue>,
    writer: protoscript.BinaryWriter,
  ): protoscript.BinaryWriter {
    if (msg.value?.length) {
      writer.writeBytes(1, msg.value);
    }
    return writer;
  },

  /**
   * @private
   */
  _readMessage: function (
    msg: BytesValue,
    reader: protoscript.BinaryReader,
  ): BytesValue {
    while (reader.nextField()) {
      const field = reader.getFieldNumber();
      switch (field) {
        case 1: {
          msg.value = reader.readBytes();
          break;
        }
        default: {
          reader.skipField();
          break;
        }
      }
    }
    return msg;
  },
};

//========================================//
//          JSON Encode / Decode          //
//========================================//

export const DoubleValueJSON = {
  /**
   * Serializes DoubleValue to JSON.
   */
  encode: function (msg: PartialDeep<DoubleValue>): string {
    return JSON.stringify(DoubleValueJSON._writeMessage(msg));
  },

  /**
   * Deserializes DoubleValue from JSON.
   */
  decode: function (json: string): DoubleValue {
    return DoubleValueJSON._readMessage(
      DoubleValueJSON.initialize(),
      JSON.parse(json),
    );
  },

  /**
   * Initializes DoubleValue with all fields set to their default value.
   */
  initialize: function (msg?: Partial<DoubleValue>): DoubleValue {
    return {
      value: 0,
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<DoubleValue>,
  ): Record<string, unknown> {
    const json: Record<string, unknown> = {};
    if (msg.value) {
      json["value"] = msg.value;
    }
    return json;
  },

  /**
   * @private
   */
  _readMessage: function (msg: DoubleValue, json: any): DoubleValue {
    const _value_ = json["value"];
    if (_value_) {
      msg.value = protoscript.parseDouble(_value_);
    }
    return msg;
  },
};

export const FloatValueJSON = {
  /**
   * Serializes FloatValue to JSON.
   */
  encode: function (msg: PartialDeep<FloatValue>): string {
    return JSON.stringify(FloatValueJSON._writeMessage(msg));
  },

  /**
   * Deserializes FloatValue from JSON.
   */
  decode: function (json: string): FloatValue {
    return FloatValueJSON._readMessage(
      FloatValueJSON.initialize(),
      JSON.parse(json),
    );
  },

  /**
   * Initializes FloatValue with all fields set to their default value.
   */
  initialize: function (msg?: Partial<FloatValue>): FloatValue {
    return {
      value: 0,
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<FloatValue>,
  ): Record<string, unknown> {
    const json: Record<string, unknown> = {};
    if (msg.value) {
      json["value"] = msg.value;
    }
    return json;
  },

  /**
   * @private
   */
  _readMessage: function (msg: FloatValue, json: any): FloatValue {
    const _value_ = json["value"];
    if (_value_) {
      msg.value = protoscript.parseDouble(_value_);
    }
    return msg;
  },
};

export const Int64ValueJSON = {
  /**
   * Serializes Int64Value to JSON.
   */
  encode: function (msg: PartialDeep<Int64Value>): string {
    return JSON.stringify(Int64ValueJSON._writeMessage(msg));
  },

  /**
   * Deserializes Int64Value from JSON.
   */
  decode: function (json: string): Int64Value {
    return Int64ValueJSON._readMessage(
      Int64ValueJSON.initialize(),
      JSON.parse(json),
    );
  },

  /**
   * Initializes Int64Value with all fields set to their default value.
   */
  initialize: function (msg?: Partial<Int64Value>): Int64Value {
    return {
      value: 0n,
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<Int64Value>,
  ): Record<string, unknown> {
    const json: Record<string, unknown> = {};
    if (msg.value) {
      json["value"] = String(msg.value);
    }
    return json;
  },

  /**
   * @private
   */
  _readMessage: function (msg: Int64Value, json: any): Int64Value {
    const _value_ = json["value"];
    if (_value_) {
      msg.value = BigInt(_value_);
    }
    return msg;
  },
};

export const UInt64ValueJSON = {
  /**
   * Serializes UInt64Value to JSON.
   */
  encode: function (msg: PartialDeep<UInt64Value>): string {
    return JSON.stringify(UInt64ValueJSON._writeMessage(msg));
  },

  /**
   * Deserializes UInt64Value from JSON.
   */
  decode: function (json: string): UInt64Value {
    return UInt64ValueJSON._readMessage(
      UInt64ValueJSON.initialize(),
      JSON.parse(json),
    );
  },

  /**
   * Initializes UInt64Value with all fields set to their default value.
   */
  initialize: function (msg?: Partial<UInt64Value>): UInt64Value {
    return {
      value: 0n,
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<UInt64Value>,
  ): Record<string, unknown> {
    const json: Record<string, unknown> = {};
    if (msg.value) {
      json["value"] = String(msg.value);
    }
    return json;
  },

  /**
   * @private
   */
  _readMessage: function (msg: UInt64Value, json: any): UInt64Value {
    const _value_ = json["value"];
    if (_value_) {
      msg.value = BigInt(_value_);
    }
    return msg;
  },
};

export const Int32ValueJSON = {
  /**
   * Serializes Int32Value to JSON.
   */
  encode: function (msg: PartialDeep<Int32Value>): string {
    return JSON.stringify(Int32ValueJSON._writeMessage(msg));
  },

  /**
   * Deserializes Int32Value from JSON.
   */
  decode: function (json: string): Int32Value {
    return Int32ValueJSON._readMessage(
      Int32ValueJSON.initialize(),
      JSON.parse(json),
    );
  },

  /**
   * Initializes Int32Value with all fields set to their default value.
   */
  initialize: function (msg?: Partial<Int32Value>): Int32Value {
    return {
      value: 0,
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<Int32Value>,
  ): Record<string, unknown> {
    const json: Record<string, unknown> = {};
    if (msg.value) {
      json["value"] = msg.value;
    }
    return json;
  },

  /**
   * @private
   */
  _readMessage: function (msg: Int32Value, json: any): Int32Value {
    const _value_ = json["value"];
    if (_value_) {
      msg.value = protoscript.parseNumber(_value_);
    }
    return msg;
  },
};

export const UInt32ValueJSON = {
  /**
   * Serializes UInt32Value to JSON.
   */
  encode: function (msg: PartialDeep<UInt32Value>): string {
    return JSON.stringify(UInt32ValueJSON._writeMessage(msg));
  },

  /**
   * Deserializes UInt32Value from JSON.
   */
  decode: function (json: string): UInt32Value {
    return UInt32ValueJSON._readMessage(
      UInt32ValueJSON.initialize(),
      JSON.parse(json),
    );
  },

  /**
   * Initializes UInt32Value with all fields set to their default value.
   */
  initialize: function (msg?: Partial<UInt32Value>): UInt32Value {
    return {
      value: 0,
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<UInt32Value>,
  ): Record<string, unknown> {
    const json: Record<string, unknown> = {};
    if (msg.value) {
      json["value"] = msg.value;
    }
    return json;
  },

  /**
   * @private
   */
  _readMessage: function (msg: UInt32Value, json: any): UInt32Value {
    const _value_ = json["value"];
    if (_value_) {
      msg.value = protoscript.parseNumber(_value_);
    }
    return msg;
  },
};

export const BoolValueJSON = {
  /**
   * Serializes BoolValue to JSON.
   */
  encode: function (msg: PartialDeep<BoolValue>): string {
    return JSON.stringify(BoolValueJSON._writeMessage(msg));
  },

  /**
   * Deserializes BoolValue from JSON.
   */
  decode: function (json: string): BoolValue {
    return BoolValueJSON._readMessage(
      BoolValueJSON.initialize(),
      JSON.parse(json),
    );
  },

  /**
   * Initializes BoolValue with all fields set to their default value.
   */
  initialize: function (msg?: Partial<BoolValue>): BoolValue {
    return {
      value: false,
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<BoolValue>,
  ): Record<string, unknown> {
    const json: Record<string, unknown> = {};
    if (msg.value) {
      json["value"] = msg.value;
    }
    return json;
  },

  /**
   * @private
   */
  _readMessage: function (msg: BoolValue, json: any): BoolValue {
    const _value_ = json["value"];
    if (_value_) {
      msg.value = _value_;
    }
    return msg;
  },
};

export const StringValueJSON = {
  /**
   * Serializes StringValue to JSON.
   */
  encode: function (msg: PartialDeep<StringValue>): string {
    return JSON.stringify(StringValueJSON._writeMessage(msg));
  },

  /**
   * Deserializes StringValue from JSON.
   */
  decode: function (json: string): StringValue {
    return StringValueJSON._readMessage(
      StringValueJSON.initialize(),
      JSON.parse(json),
    );
  },

  /**
   * Initializes StringValue with all fields set to their default value.
   */
  initialize: function (msg?: Partial<StringValue>): StringValue {
    return {
      value: "",
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<StringValue>,
  ): Record<string, unknown> {
    const json: Record<string, unknown> = {};
    if (msg.value) {
      json["value"] = msg.value;
    }
    return json;
  },

  /**
   * @private
   */
  _readMessage: function (msg: StringValue, json: any): StringValue {
    const _value_ = json["value"];
    if (_value_) {
      msg.value = _value_;
    }
    return msg;
  },
};

export const BytesValueJSON = {
  /**
   * Serializes BytesValue to JSON.
   */
  encode: function (msg: PartialDeep<BytesValue>): string {
    return JSON.stringify(BytesValueJSON._writeMessage(msg));
  },

  /**
   * Deserializes BytesValue from JSON.
   */
  decode: function (json: string): BytesValue {
    return BytesValueJSON._readMessage(
      BytesValueJSON.initialize(),
      JSON.parse(json),
    );
  },

  /**
   * Initializes BytesValue with all fields set to their default value.
   */
  initialize: function (msg?: Partial<BytesValue>): BytesValue {
    return {
      value: new Uint8Array(),
      ...msg,
    };
  },

  /**
   * @private
   */
  _writeMessage: function (
    msg: PartialDeep<BytesValue>,
  ): Record<string, unknown> {
    const json: Record<string, unknown> = {};
    if (msg.value?.length) {
      json["value"] = protoscript.serializeBytes(msg.value);
    }
    return json;
  },

  /**
   * @private
   */
  _readMessage: function (msg: BytesValue, json: any): BytesValue {
    const _value_ = json["value"];
    if (_value_) {
      msg.value = protoscript.parseBytes(_value_);
    }
    return msg;
  },
};
