name: Publish NPM Package
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: tatethurston/github-actions/publish@main
        with:
          package_directory: packages/protoscript
          npm_token: ${{ secrets.NPM_TOKEN }}
